# GitHub Actions workflow for testing and continuous integration.
#
# The tests are run with tox and the test environments configured by
# tox.ini.

name: Python Tests

on: [push, pull_request]

jobs:
  # Test with Astropy development version
  build_docs:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      TOXENV: py38-test
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: ${{ env.TOXENV }} (${{ matrix.os }})
      run: |
        python -c "import sys; print(f'Python {sys.version}')"
        python -c "import pip; print(f'pip {pip.__version__}')"
        tox -e $TOXENV
