# GitHub Actions workflow for testing and continuous integration.
#
# The tests are run with tox and the test environments configured by
# tox.ini.

name: Python Tests

on: [push, pull_request]

jobs:
  # Test with Astropy development version
  build_docs:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      TOXENV: py36-test-alldeps-astropylts-numpy117
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: $TOXENV (${{ matrix.os }})
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Testing building of docs using tox
      run: |
        #tox -e $TOXENV
        python -c "import sys; print(sys.version)"
