# need to add i386 job

# GitHub Actions workflow for testing and continuous integration.
#
# The tests are run with tox and the test environments configured by
# tox.ini.
name: Tox matrix

on: [push, pull_request]

jobs:

  main_matrix:
    name: ${{ matrix.os }}, ${{ matrix.python-version }}-${{ matrix.tox-env }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        exclude:
          - os: macos-latest
            python-version: 3.6
          - os: macos-latest
            python-version: 3.7
          - os: macos-latest
            python-version: 3.9
          - os: windows-latest
            python-version: 3.6
          - os: windows-latest
            python-version: 3.7
          - os: windows-latest
            python-version: 3.9

            #env:
            #- TOXENV: alldeps-cov
        tox-env: ['alldeps-cov']
        #env:
        #TOXENV: ${{ steps.pyver.outputs.pyver }}-test-${{ matrix.tox-env }}
    steps:

    - name: Define tox environment name
      id: toxenv
      shell: bash
      #run: echo ::set-env name=toxenv::$(python -c "print('py'+'${{ matrix.python-version }}'.replace('.', '') + '-${{ matrix.tox-env }}')")
      run: echo toxenv=$(python -c "print('py'+'${{ matrix.python-version }}'.replace('.', '') + '-${{ matrix.tox-env }}')") >> $GITHUB_ENV

    #- name: Define tox environment name
    #  id: toxenv
    #  run: |
    #    ##$pyver=$(python -c "a='${{ matrix.python-version }}'; a=a.replace('.', ''); print(a)")
    #    #pyver=$(python -c "print('${{ matrix.python-version }}'.replace('.', ''))")
    #    ##$pyver = "${{ matrix.python-version }}" -replace '.', ''
    #    ##$pyver = "${{ matrix.python-version }}".replace('.', '')
    #    #toxenv="py$pyver-${{ matrix.tox-env }}"
    #    #echo "::set-output name=toxenv::$toxenv"
    #    echo ::set-output name=toxenv::$(python -c "print('py'+'${{ matrix.python-version }}'.replace('.', '') + '${{ matrix.tox-env }}')")

    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Print Python, pip, setuptools, and tox versions
      run: |
        python -c "import sys; print(f'Python {sys.version}')"
        python -c "import pip; print(f'pip {pip.__version__}')"
        python -c "import setuptools; print(f'setuptools {setuptools.__version__}')"
        python -c "import tox; print(f'tox {tox.__version__}')"
    - name: ${{ env.toxenv }} (${{ matrix.os }})
      run: |
        echo ${{ matrix.tox-env }}
        #tox -e ${{ matrix.tox-env }}

  py38_matrix:
    name: ${{ matrix.os }}, ${{ matrix.python-version }}-${{ matrix.tox-env }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
        env:
          - TOXENV: test
          - TOXENV: test-alldeps-devdeps
          - TOXENV: codestyle
          - TOXENV: build_docs
          - TOXENV: linkcheck
    steps:
      #- name: Define Python version
      #  id: pyver
      # run: |
      #   pyver=$(echo {{ matrix.python-version }} | tr -d '.')
      #   echo "::set-output name=id::$pyver"
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
        sudo apt-get -y install graphviz
    - name: Print Python, pip, setuptools, and tox versions
      run: |
        python -c "import sys; print(f'Python {sys.version}')"
        python -c "import pip; print(f'pip {pip.__version__}')"
        python -c "import setuptools; print(f'setuptools {setuptools.__version__}')"
        python -c "import tox; print(f'tox {tox.__version__}')"
    - name: ${{ matrix.env.TOXENV }} (${{ matrix.os }})
      run: |
        echo ${{ matrix.env.TOXENV }}
        #tox -e ${{ matrix.env.TOXENV }}

  astropy_lts:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6]
        env:
          - TOXENV: test-alldeps-astropylts-numpy117
    steps:
      #- name: Define Python version
      #  id: pyver
      # run: |
      #   pyver=$(echo {{ matrix.python-version }} | tr -d '.')
      #   echo "::set-output name=id::$pyver"
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Print Python, pip, setuptools, and tox versions
      run: |
        python -c "import sys; print(f'Python {sys.version}')"
        python -c "import pip; print(f'pip {pip.__version__}')"
        python -c "import setuptools; print(f'setuptools {setuptools.__version__}')"
        python -c "import tox; print(f'tox {tox.__version__}')"
    - name: ${{ matrix.env.TOXENV }} (${{ matrix.os }})
      run: |
        echo ${{ matrix.env.TOXENV }}
        #tox -e ${{ matrix.env.TOXENV }}
